# Puerto (puedes sobreescribir con APP_PORT o SERVER_PORT en .env)
server.port=${SERVER_PORT:8090}

spring.application.name=game-5inline-service
spring.main.allow-circular-references=true

# RabbitMQ: usa variables de entorno si existen, si no utiliza los valores por defecto
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:${RABBITMQ_HOST:localhost}}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:${RABBITMQ_PORT:5672}}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:${RABBITMQ_USERNAME:guest}}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:${RABBITMQ_PASSWORD:guest}}

# Opcional: perfil por defecto
spring.profiles.active=${SPRING_PROFILES_ACTIVE:default}
